version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
      - NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT}
    environment:
      NODE_ENV: production
    
    env_file:
      - .env.prod
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - pttkht-network

networks:
  pttkht-network:
    external: true